### PR TITLE
Adding Vagrantfile for spinning up a development VM

### PR DESCRIPTION
**Pull request by Yuval-Vino**
After running 'vagrant up' the application can be accessed at:
> http://127.0.0.1:8000/
#3 relevant issue

### CODE REVIEW

**Comment by ErezCohenn** [comment]
The file is looking good!

**Comment by Yuval-Vino** [comment]
> 

You're right!, I've added the gitignore check it out!
about the description, of course, we need to wait for Tamir's tasks but it seems kinda useless without it so  I preceded it

**Comment by Yuval-Vino** [comment]
> Which issue is this PR relevant to? please link it.

Added to description

**Comment by Omeramsc** [comment]
> > Which issue is this PR relevant to? please link it.
> 
> Added to description

Note that there are specific keywords  that links an issue to a PR.
you can take a look here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by Omeramsc — APPROVED** [review]

**Review by ErezCohenn — APPROVED** [review]

**Review by tamirmatok — APPROVED** [review]

**Review by ormergi — APPROVED** [review]
Looks good to me

**Pull request merged**
